FROM node:12.22-bullseye

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

RUN apt-get update && apt-get install -y python3-pip
RUN pip install numpy tensorflow

COPY . .

ENTRYPOINT npm run start:server