FROM tensorflow/tensorflow

RUN apt-get update && apt-get install -y nodejs
RUN pip install numpy
RUN apt install -y npm

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install


COPY . .

ENV PYTHONUNBUFFERED=1
ENTRYPOINT npm run start:server